/**
 * Vault Organization Types
 *
 * Type definitions for intelligent vault organization, content analysis,
 * and automated file reorganization with link updating capabilities.
 */

// ============================================
// Vault File Information
// ============================================

/**
 * Content metadata extracted from a vault file
 *
 * Includes structural information like headings, frontmatter,
 * and relationship data like links and backlinks.
 */
export interface ContentMetadata {
  /** Top-level headings extracted from the file */
  readonly headings: readonly string[];
  /** YAML frontmatter key-value pairs */
  readonly frontmatter: Readonly<Record<string, unknown>>;
  /** Word count of the file content */
  readonly wordCount: number;
  /** Internal wiki-links found in the file */
  readonly links: readonly string[];
  /** Files that link to this file */
  readonly backlinks: readonly string[];
  /** Code blocks language identifiers */
  readonly codeBlocks: readonly string[];
  /** Tags found in the file (including frontmatter tags) */
  readonly tags: readonly string[];
}

/**
 * Represents a single file in the vault with metadata
 *
 * Contains both filesystem information and content analysis results.
 */
export interface VaultFileInfo {
  /** Full path relative to vault root */
  readonly path: string;
  /** Filename without path */
  readonly name: string;
  /** File extension (e.g., 'md', 'pdf') */
  readonly extension: string;
  /** File size in bytes */
  readonly size: number;
  /** Creation timestamp (ISO 8601) */
  readonly created: string;
  /** Last modification timestamp (ISO 8601) */
  readonly modified: string;
  /** Content metadata (only available for markdown files) */
  readonly contentMetadata?: ContentMetadata;
  /** Extracted keywords from content */
  readonly keywords: readonly string[];
  /** Identified topics/themes */
  readonly topics: readonly string[];
}

// ============================================
// Vault Structure
// ============================================

/**
 * Category statistics for vault organization
 *
 * Tracks files grouped by their inferred category or folder.
 */
export interface CategoryStats {
  /** Number of files in this category */
  readonly fileCount: number;
  /** Total size of files in bytes */
  readonly totalSize: number;
  /** File paths belonging to this category */
  readonly files: readonly string[];
  /** Average confidence score for category assignments */
  readonly avgConfidence: number;
}

/**
 * Folder statistics in the vault
 *
 * Provides metadata about vault folder structure and contents.
 */
export interface FolderStats {
  /** Number of files directly in this folder (non-recursive) */
  readonly fileCount: number;
  /** Number of subfolders */
  readonly subfolderCount: number;
  /** Total size of files in bytes */
  readonly totalSize: number;
  /** List of file paths in this folder */
  readonly files: readonly string[];
}

/**
 * Represents the complete analyzed structure of a vault
 *
 * Provides a comprehensive view of vault organization including
 * files, folders, and categorization.
 */
export interface VaultStructure {
  /** Absolute path to vault root */
  readonly rootPath: string;
  /** Total number of files in vault */
  readonly totalFiles: number;
  /** Total size of all files in bytes */
  readonly totalSize: number;
  /** Timestamp when structure was analyzed (ISO 8601) */
  readonly analyzedAt: string;
  /** All files with their metadata */
  readonly files: readonly VaultFileInfo[];
  /** Folder path -> folder statistics */
  readonly folders: Readonly<Record<string, FolderStats>>;
  /** Category name -> category statistics */
  readonly categories: Readonly<Record<string, CategoryStats>>;
  /** Orphan files (no incoming or outgoing links) */
  readonly orphanFiles: readonly string[];
}

// ============================================
// Content Analysis
// ============================================

/**
 * Content analysis result for a single file
 *
 * Generated by AI-powered content analysis to understand
 * file purpose, topics, and suggest better organization.
 */
export interface ContentAnalysis {
  /** File path that was analyzed */
  readonly filePath: string;
  /** AI-generated summary of file content */
  readonly summary: string;
  /** Identified topics/themes in priority order */
  readonly topics: readonly string[];
  /** Extracted keywords */
  readonly keywords: readonly string[];
  /** Suggested category for organization */
  readonly suggestedCategory: string;
  /** Suggested filename (if current name is unclear) */
  readonly suggestedName?: string;
  /** Confidence score (0-1) for suggestions */
  readonly confidence: number;
  /** Related files based on content similarity */
  readonly relatedFiles: readonly string[];
  /** Reason for suggestions */
  readonly reasoning: string;
}

// ============================================
// Organization Suggestions
// ============================================

/**
 * Type of reorganization operation
 */
export type ReorganizationType = 'rename' | 'move' | 'both';

/**
 * Impact assessment for a reorganization operation
 *
 * Quantifies the effects of making a change.
 */
export interface OperationImpact {
  /** Number of files that link to this file */
  readonly affectedFiles: number;
  /** Total number of links that need updating */
  readonly linksToUpdate: number;
  /** Files that will become broken links if not updated */
  readonly potentialBrokenLinks: readonly string[];
  /** Estimated complexity (low, medium, high) */
  readonly complexity: 'low' | 'medium' | 'high';
}

/**
 * Single reorganization suggestion
 *
 * Represents one recommended change to improve vault organization.
 */
export interface OrganizationSuggestion {
  /** Type of operation */
  readonly type: ReorganizationType;
  /** Current file path */
  readonly currentPath: string;
  /** Suggested new path (for move) */
  readonly suggestedPath?: string;
  /** Suggested new name (for rename) */
  readonly suggestedName?: string;
  /** Human-readable reason for suggestion */
  readonly reason: string;
  /** Confidence score (0-1) */
  readonly confidence: number;
  /** Impact assessment */
  readonly impact: OperationImpact;
  /** Category this file would belong to after reorganization */
  readonly targetCategory?: string;
}

// ============================================
// Organization Plan
// ============================================

/**
 * Warning or issue with the organization plan
 */
export interface OrganizationWarning {
  /** Warning severity level */
  readonly severity: 'info' | 'warning' | 'error';
  /** File path related to warning */
  readonly filePath?: string;
  /** Warning message */
  readonly message: string;
  /** Suggested action to resolve */
  readonly suggestion?: string;
}

/**
 * Estimated impact of executing the organization plan
 *
 * Provides metrics before committing to changes.
 */
export interface EstimatedImpact {
  /** Total files to be moved */
  readonly filesToMove: number;
  /** Total files to be renamed */
  readonly filesToRename: number;
  /** Total links to be updated across all files */
  readonly linksToUpdate: number;
  /** Files that will be modified to update links */
  readonly filesRequiringLinkUpdates: number;
  /** Estimated time to complete (in milliseconds) */
  readonly estimatedDuration: number;
  /** Whether any risky operations are included */
  readonly hasRiskyOperations: boolean;
}

/**
 * Complete reorganization plan
 *
 * Contains all suggestions and impact analysis for vault reorganization.
 */
export interface OrganizationPlan {
  /** Timestamp when plan was generated (ISO 8601) */
  readonly generatedAt: string;
  /** All reorganization suggestions */
  readonly suggestions: readonly OrganizationSuggestion[];
  /** Overall estimated impact */
  readonly estimatedImpact: EstimatedImpact;
  /** Warnings and issues */
  readonly warnings: readonly OrganizationWarning[];
  /** High-level summary of the plan */
  readonly summary: string;
  /** Whether the plan is safe to execute automatically */
  readonly requiresManualReview: boolean;
}

// ============================================
// Reorganization Execution
// ============================================

/**
 * Type of reorganization operation to execute
 */
export type OperationType = 'rename' | 'move' | 'delete' | 'update_links';

/**
 * Rollback information for an operation
 *
 * Allows undoing changes if something goes wrong.
 */
export interface RollbackInfo {
  /** Original file path */
  readonly originalPath: string;
  /** Original file content (for content changes) */
  readonly originalContent?: string;
  /** Original file location (for moves) */
  readonly originalLocation?: string;
  /** Timestamp when operation was performed (ISO 8601) */
  readonly timestamp: string;
}

/**
 * Single reorganization operation to execute
 *
 * Represents one atomic operation in the reorganization process.
 */
export interface ReorganizationOperation {
  /** Unique operation ID */
  readonly id: string;
  /** Type of operation */
  readonly type: OperationType;
  /** Source file path */
  readonly sourcePath: string;
  /** Target file path (for move/rename) */
  readonly targetPath?: string;
  /** New content (for link updates) */
  readonly newContent?: string;
  /** Rollback information */
  readonly rollbackInfo: RollbackInfo;
  /** Operation status */
  readonly status: 'pending' | 'completed' | 'failed';
  /** Error message if failed */
  readonly error?: string;
}

// ============================================
// Reorganization Result
// ============================================

/**
 * Statistics about a failed operation
 */
export interface FailedOperation {
  /** The operation that failed */
  readonly operation: ReorganizationOperation;
  /** Error message */
  readonly error: string;
  /** Error code (if applicable) */
  readonly errorCode?: string;
  /** Whether rollback was successful */
  readonly rollbackSuccessful: boolean;
}

/**
 * Result of executing a reorganization plan
 *
 * Contains detailed information about what succeeded and failed.
 */
export interface ReorganizationResult {
  /** Whether overall reorganization was successful */
  readonly success: boolean;
  /** Timestamp when reorganization started (ISO 8601) */
  readonly startedAt: string;
  /** Timestamp when reorganization completed (ISO 8601) */
  readonly completedAt: string;
  /** Operations that completed successfully */
  readonly operations: readonly ReorganizationOperation[];
  /** Operations that failed */
  readonly failedOperations: readonly FailedOperation[];
  /** Number of links updated across all files */
  readonly linksUpdated: number;
  /** Files that were modified */
  readonly filesModified: readonly string[];
  /** Whether rollback is available */
  readonly rollbackAvailable: boolean;
  /** Path to rollback state file (if saved) */
  readonly rollbackStatePath?: string;
  /** Human-readable summary */
  readonly summary: string;
}

// ============================================
// Analysis Options
// ============================================

/**
 * Options for vault structure analysis
 */
export interface AnalysisOptions {
  /** Whether to include content analysis (slower) */
  readonly includeContentAnalysis?: boolean;
  /** File patterns to exclude (glob patterns) */
  readonly excludePatterns?: readonly string[];
  /** Maximum file size to analyze in bytes */
  readonly maxFileSize?: number;
  /** Whether to analyze orphan files */
  readonly detectOrphans?: boolean;
  /** Whether to extract keywords using NLP */
  readonly extractKeywords?: boolean;
}

/**
 * Options for generating organization suggestions
 */
export interface SuggestionOptions {
  /** Minimum confidence threshold (0-1) */
  readonly minConfidence?: number;
  /** Maximum number of suggestions to generate */
  readonly maxSuggestions?: number;
  /** Target folder structure (preferred categories) */
  readonly targetStructure?: readonly string[];
  /** Whether to suggest renames for unclear filenames */
  readonly suggestRenames?: boolean;
  /** Whether to consolidate related files */
  readonly consolidateRelated?: boolean;
}

/**
 * Options for executing reorganization
 */
export interface ExecutionOptions {
  /** Perform dry run without making changes */
  readonly dryRun?: boolean;
  /** Create backup before executing */
  readonly createBackup?: boolean;
  /** Backup location path */
  readonly backupPath?: string;
  /** Update links in other files */
  readonly updateLinks?: boolean;
  /** Stop on first error */
  readonly stopOnError?: boolean;
  /** Skip operations below confidence threshold */
  readonly skipLowConfidence?: boolean;
  /** Minimum confidence to execute (0-1) */
  readonly minExecutionConfidence?: number;
}

// ============================================
// Custom Error Classes
// ============================================

/**
 * Error during vault analysis
 *
 * Thrown when analyzing vault structure or content fails.
 */
export class VaultAnalysisError extends Error {
  constructor(
    message: string,
    public readonly path?: string,
    public readonly cause?: unknown
  ) {
    super(message);
    this.name = 'VaultAnalysisError';
    Object.setPrototypeOf(this, VaultAnalysisError.prototype);
  }
}

/**
 * Error during vault reorganization
 *
 * Thrown when executing reorganization operations fails.
 */
export class VaultReorganizationError extends Error {
  constructor(
    message: string,
    public readonly operation?: ReorganizationOperation,
    public readonly rollbackAvailable?: boolean,
    public readonly cause?: unknown
  ) {
    super(message);
    this.name = 'VaultReorganizationError';
    Object.setPrototypeOf(this, VaultReorganizationError.prototype);
  }
}

/**
 * Error when rollback operation fails
 *
 * Critical error that indicates data may be in inconsistent state.
 */
export class RollbackError extends Error {
  constructor(
    message: string,
    public readonly failedOperations: readonly ReorganizationOperation[],
    public readonly cause?: unknown
  ) {
    super(message);
    this.name = 'RollbackError';
    Object.setPrototypeOf(this, RollbackError.prototype);
  }
}

// ============================================
// Utility Types
// ============================================

/**
 * Filter criteria for vault files
 */
export interface FileFilter {
  /** Filter by file extension */
  readonly extensions?: readonly string[];
  /** Filter by minimum file size */
  readonly minSize?: number;
  /** Filter by maximum file size */
  readonly maxSize?: number;
  /** Filter by date range */
  readonly dateRange?: {
    readonly from?: string; // ISO 8601
    readonly to?: string; // ISO 8601
  };
  /** Filter by folder path */
  readonly folders?: readonly string[];
  /** Filter by tags */
  readonly tags?: readonly string[];
  /** Filter by orphan status */
  readonly orphansOnly?: boolean;
}

/**
 * Sort criteria for vault files
 */
export type SortCriteria =
  | 'name'
  | 'size'
  | 'created'
  | 'modified'
  | 'path'
  | 'wordCount'
  | 'linkCount';

/**
 * Sort options
 */
export interface SortOptions {
  /** Sort by criteria */
  readonly by: SortCriteria;
  /** Sort direction */
  readonly direction: 'asc' | 'desc';
}

/**
 * Pagination options for large result sets
 */
export interface PaginationOptions {
  /** Page number (0-based) */
  readonly page: number;
  /** Items per page */
  readonly pageSize: number;
}

/**
 * Paginated result wrapper
 */
export interface PaginatedResult<T> {
  /** Items in current page */
  readonly items: readonly T[];
  /** Current page number (0-based) */
  readonly page: number;
  /** Items per page */
  readonly pageSize: number;
  /** Total number of items */
  readonly total: number;
  /** Total number of pages */
  readonly totalPages: number;
  /** Whether there's a next page */
  readonly hasNext: boolean;
  /** Whether there's a previous page */
  readonly hasPrevious: boolean;
}
